rake db:import:happy_member
#rake db:import:board_guin
#rake db:import:sellnbuy
#rake db:import:well_being
#rake db:import:board_story_travel
#rake db:import:sharenrent
#rake db:import:study
#rake db:import:immigration
#rake db:import:taxnsuper
#rake db:import:law
