TopFeedList.category_feed(Immigration.name).destroy_all
Immigration.destroy_all

admin = Admin.post_admin.first

expiry = Common.current_time + 60.days

post = Immigration.new(:subject => 'JJ 이민센터', :category => Immigration::Categories[:for_immigration], :valid_until => expiry)
post.save
image = Image.new(:avatar => File.new("db/import/jj_2.jpg"))
image.attached_to_by(post, admin)
image_body = Image.new(:avatar => File.new("db/import/jj_3.jpg"))
image_body.attached_to_by(post, admin)
image = Image.new(:avatar => File.new("db/import/jj_4.jpg"))
image.attached_to_by(post, admin)

post.set_user(admin)
html = <<-HTML
<img src="#{image_body.original_image}"/>
<span style="font-size: 13px"><span style="font-family: 굴림">
&nbsp;</p>
<span style="font-size: 12px">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: Arial"><o:p></o:p></span></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><b style="mso-bidi-font-weight: normal"><u><br>
JJ<span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민센터</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">법무사</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">소개</span></u></b></span><span style="font-family: 궁서"></span><span style="font-family: 궁서"></span></span></p>
</span>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><font face="Batang"><b style="mso-bidi-font-weight: normal"><u><span style="font-family: Arial; font-size: 14pt"><o:p></o:p></span></u></b></font></span></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><span style="font-size: 11px"><span style="font-family: Arial"><o:p></o:p></span></span></span></p>
<span style="font-size: 13px"><span style="font-family: 굴림">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
</span></span><span style="font-size: 12px">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">법무사</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">박기석</span> (Brian K. PARK)</span></span></p>
</span>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
<span style="font-size: 13px">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</span><span style="font-size: 12px"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span>JJ<span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민센터</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">대표법무사</span></span><span style="font-family: 궁서"></span></span>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">호주</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">연방정부</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민성</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">공인</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민법무사</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>MARN 0960412</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>Graduate Certificate in Australian Migration Law and Practice, Griffith University, Brisbane, Australia</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>Master of Commerce (Advanced) in Professional Accounting, University of Queensland, Brisbane, Australia</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>Bachelor of Business, 연세대학교 경영학과 졸업, Seoul, Korea</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>KEY2HOJU <span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민법률사무소</span> Senior Partner</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>Australia Post Administration Officer</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">한양증권</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">법인영업팀</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">법인영업</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">담당</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">동화약품</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">경영기획팀</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">예산</span>/<span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">재무</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">담당</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l1 level1 lfo3; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">삼성증권</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">기업금융팀</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">기업분석</span>/IPO <span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">담당</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><span style="font-size: 11px"><span style="font-family: Arial"><o:p></o:p></span></span></span></p>
<span style="font-size: 13px"><span style="font-family: 굴림">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
</span></span><span style="font-family: 궁서">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
</span><span style="font-size: 13px"><span style="font-family: 궁서">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><o:p><span style="font-family: 굴림">&nbsp;</span></o:p></p>
</span></span><span style="font-size: 12px">&nbsp;</span>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><span style="font-size: 11px"><span style="font-family: Arial"><o:p></o:p></span></span></span></p>
<span style="font-size: 12px">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: Arial"><o:p></o:p></span></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><b style="mso-bidi-font-weight: normal"><u>JJ<span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민센터</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">서비스</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">소개</span></u></b></span><span style="font-family: 궁서"></span><span style="font-family: 궁서"></span></span></p>
</span>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><font face="Batang"><b style="mso-bidi-font-weight: normal"><u><span style="font-family: Arial; font-size: 14pt"><o:p></o:p></span></u></b></font></span></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><span style="font-size: 11px"><span style="font-family: Arial"><o:p></o:p></span></span></span></p>
<span style="font-size: 13px"><span style="font-family: 굴림">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
</span></span><span style="font-size: 12px">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: Arial"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">포괄적인</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">비자관련</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">상담서비스</span></span><span style="font-family: 궁서"></span></span></p>
</span>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">기술이민</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">관련</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">업무</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">사업/투자이민</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">관련</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">업무</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">취업이민</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">관련</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">업무</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">가족이민</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">관련</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">업무</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt 'Times New Roman'">&nbsp;&nbsp; </span></span></span>MRT/RRT <span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">등</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">재심청구</span></span></span><font face="Batang"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></font></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 13px"><span style="font-family: 굴림"></span><span style="font-size: 11px"><span style="font-family: Arial"><o:p></o:p></span></span></span></p>
<span style="font-size: 13px"><span style="font-family: 굴림">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
</span></span><span style="font-family: 궁서">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"><b style="mso-bidi-font-weight: normal"><u>JJ</u></b><b style="mso-bidi-font-weight: normal"><u><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민센터</span></u></b><b style="mso-bidi-font-weight: normal"><u><span lang="KO"> </span></u></b><b style="mso-bidi-font-weight: normal"><u><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">위치</span></u></b><b style="mso-bidi-font-weight: normal"><u><span lang="KO"> </span></u></b><b style="mso-bidi-font-weight: normal"><u><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">및</span></u></b><b style="mso-bidi-font-weight: normal"><u><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">연락처</span></u></b></span></span><font face="Batang"><b style="mso-bidi-font-weight: normal"><u><span style="font-family: Arial; font-size: 14pt"><o:p></o:p></span></u></b></font></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"></span><span style="font-size: 13px"><span style="font-family: Arial"><o:p><span style="font-family: 굴림">&nbsp;</span></o:p></span></span></span></p>
<span style="font-family: 굴림">
<p style="margin: 0cm 0cm 0pt" class="MsoNormal"><span style="font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-size: 13px"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp; </span></span></span>Address: Suite 2E, Level 2, 235 Edward Street, Brisbane, QLD 4000</span></p>
</span>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp; </span></span></span>Tel: +61 (0)7 3211 0077</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp; </span></span></span>Fax: +61 (0)7 3211 0079</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp; </span></span></span>Internet Phone: 070 8793 1840</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp; </span></span></span>Mobile: +61 (0)401 830 560</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="text-indent: -20pt; margin: 0cm 0cm 0pt 40pt; mso-list: l0 level1 lfo1; tab-stops: list 40.0pt" class="MsoNormal"><span style="font-family: 굴림"><span style="font-size: 13px"><span style="mso-bidi-font-family: Wingdings; mso-fareast-font-family: Wingdings"><span style="mso-list: Ignore">&nbsp;<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp; </span></span></span>E-mail: key2hoju@gmail.com</span></span><span style="font-family: Arial; font-size: 12pt"><o:p></o:p></span></p>
<p style="margin: 0cm 0cm 0pt" class="MsoNormal">&nbsp;</p>
</span></span></span><span style="font-family: 돋움"><span style="font-family: 굴림"><span style="font-size: 13px"><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">먼저</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">저희</span> JJ<span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">이민센터를</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">방문해</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">주셔서</span><span lang="KO"> </span><span style="mso-bidi-font-family: Arial; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial" lang="KO">감사합니다</span>.</span></span> </span>
</span>
HTML
content = post.build_content(:body => html)
content.save

